### ISSUE TITLE
done

### ISSUE THREAD

**Issue by hiepeng** [sizifart/SeedCoinBot#9]
done

**Comment by Bebenmahardika** [comment]
QUANTITY_TO_KEEP

how your setting this ?

**Comment by Pawansingh333** [comment]
same error

**Comment by hiepeng** [comment]
> QUANTITY_TO_KEEP
> 
> how your setting this ?

Im not setting, I am setting sell false

**Comment by hiepeng** [comment]
> same error

how to fix?
